package br.com.cogerh.template.util;

/**
 * CLASSE ONDE ARMAZENA TODAS AS PERMISSÕES PADRÃO DO SISTEMA
 * @author alyssonnascimento
 *
 */
public class PermissaoPadrao {

	public final static String TELA_DETALHAMENTO_CHAMADO = "TELA_DETALHAMENTO_CHAMADO";

	
	
	public final static String BOTAO_DETALHAMENTO_FINALIZAR_CHAMADO = "BOTAO_DETALHAMENTO_FINALIZAR_CHAMADO";
	public final static String BOTAO_DETALHAMENTO_TRABALHAR_CHAMADO = "BOTAO_DETALHAMENTO_TRABALHAR_CHAMADO";
	public final static String BOTAO_DETALHAMENTO_ALOCAR_TECNICO_CHAMADO = "BOTAO_DETALHAMENTO_ALOCAR_TECNICO_CHAMADO";
	public final static String BOTAO_DETALHAMENTO_SOLICITAR_VIABILIDADE = "BOTAO_DETALHAMENTO_SOLICITAR_VIABILIDADE";
	public final static String BOTAO_DETALHAMENTO_EDITAR_CHAMADO = "BOTAO_DETALHAMENTO_EDITAR_CHAMADO";
	public final static String BOTAO_DETALHAMENTO_APROVAR_CHAMADO = "BOTAO_DETALHAMENTO_APROVAR_CHAMADO";
	public final static String BOTAO_DETALHAMENTO_REPROVAR_CHAMADO = "BOTAO_DETALHAMENTO_REPROVAR_CHAMADO";
	public final static String BOTAO_DETALHAMENTO_INCLUIR_ACOMPANHAMENTO = "BOTAO_DETALHAMENTO_INCLUIR_ACOMPANHAMENTO";
	public final static String BOTAO_DETALHAMENTO_INCLUIR_ANEXO = "BOTAO_DETALHAMENTO_INCLUIR_ANEXO";
	public final static String BOTAO_DETALHAMENTO_VOLTAR = "BOTAO_DETALHAMENTO_VOLTAR";
	public final static String VISUALIZAR_DETALHAMENTO_CHAMADO = "VISUALIZAR_DETALHAMENTO_CHAMADO";

	
	


	
	

}
